# Generated by Django 4.0.2 on 2022-02-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='RecipeModel',
        ),
    ]
